### ISSUE TITLE
Crash with "ERROR: DownMedia[Script Filter] Code 1: ... `spawn': Permission denied"

### ISSUE THREAD

**Issue by dollar2048** [vitorgalvao/alfred-workflows#100]
#### Setup info

* Workflow name: DownMedia
* Workflow version: 2020.1
* Alfred version: 4.0.8
* macOS version: 10.15.2
* `download_dir` set to `~/Downloads`

#### Description of issue

I have moved to the new MacBook and migrated all my Alfred settings.
So this workflow worked on the previous machine and not on the new one.

#### Steps to reproduce:
1. copy link https://www.youtube.com/watch?v=7HgbcTqxoN4
2. open Alfred and type `dv`
3. `DownMedia` workflow "crashes" with the following debug output

#### Debugger output

```
[20:23:34.550] DownMedia[Script Filter] Queuing argument ''
[20:23:34.806] DownMedia[Script Filter] Script with argv '' finished
[20:23:34.818] ERROR: DownMedia[Script Filter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `spawn': Permission denied - /Users/sergei.prikhodko/Google (Errno::EACCES)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:159:in `popen2'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:342:in `capture2'
	from /Users/sergei.prikhodko/Google Drive/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B30E4DEE-38A2-4DCC-A1A8-8B293B5C82B1/downmedia_functions.rb:216:in `get_title_url'
	from /Users/sergei.prikhodko/Google Drive/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B30E4DEE-38A2-4DCC-A1A8-8B293B5C82B1/downmedia_functions.rb:20:in `show_options'
	from /Users/sergei.prikhodko/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/762003D4-17D6-40EA-B1EC-739AE4C55B44:3:in `<main>'
```

**Comment by vitorgalvao** [comment]
Looks like something Catalina should have asked for permission for but didn’t.

1. What was your frontmost app at the moment of the crash?
2. Does it still crash if you put Chrome or Safari (or another browser except Firefox, which has no AppleScript support) in front?
3. What’s your usual browser?

**Comment by dollar2048** [comment]
1. Safari.
2. Yes.
3. Safari.

BTW, I have tried to reinstall it. 
I also tried to install old version `1.22.14`
on version `1.22.14` I have the following error:
[`22:28:49.566] ERROR: DownVid[Run Script] /Users/sergei.prikhodko/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/149FDCFE-C3CC-49DC-B363-EA577FED3868: line 1: ./downvid: Permission denied
`

**Comment by vitorgalvao** [comment]
If it’s giving you errors on a version that used to be working, it does seem like the issue lies somewhere else. Seeing as you’re on a new machine, have you [given Alfred the correct permissions](https://www.alfredapp.com/help/getting-started/permissions/)?

**Comment by dollar2048** [comment]
yes. 
I have checked it again.
Looks like all possible permissions are given.
Is there any way I can debug what goes wrong?

**Comment by vitorgalvao** [comment]
> Is there any way I can debug what goes wrong?

I’m not on Catalina (precisely due to its bugginess) so it’s hard for me to guess where the issue lies. I’ll need someone else to give an insight or more information. The Workflow was just updated, so it should start to happen soon. Then again it might not, if the issue is only on your setup.

You can try the old version and fix the error by navigating to its directory and running `chmod +x downvid` to see if it fixes the permission issue. As for the new version, maybe try giving automation permissions to the `get_title_and_url.js` file inside. I’m mostly shooting in the dark, though, as it’s hard to debug what I can’t reproduce.

**Comment by dollar2048** [comment]
On old version after running `chmod +x downvid`
I have a new error now
```
[23:03:05.097] ERROR: DownVid[Run Script] ./downvid: line 5: ./_sharedresources: Permission denied
./downvid: line 8: sed: No such file or directory
./downvid: line 9: sed: No such file or directory
./downvid: line 13: awk: No such file or directory
./downvid: line 14: awk: No such file or directory
./downvid: line 15: awk: No such file or directory
./downvid: line 16: awk: No such file or directory
./downvid: line 46: youtube-dl: No such file or directory
./downvid: line 50: basename: No such file or directory
./downvid: line 38: ./Notificator.app/Contents/Resources/Scripts/notificator: Permission denied
```

so now it is getting further.

**Comment by vitorgalvao** [comment]
> so now it is getting further.

In theory, yes. In practice, it seems the setup is more borked than initially though.

Apologies, but I don’t have the bandwidth to keep debugging this. My Workflows are distributed for free and the time I spend debugging other people’s issues has a very real toll. It becomes even higher when you consider we are debugging and older version of a Workflow that just got a major overhaul—it’s a bad use of time.

I’m open to fixing bugs in my code, but I literally cannot afford to keep looking into an issue that is caused either by an odd setup or Apple’s lack of commitment to software quality.

If I get new bug reports for the new version, I’ll look into it.

**Comment by dollar2048** [comment]
I found the core of the problem after a few hours or investigating.
I have Alfred setting in the folder with " " in the name. E.g. `.../Google Drive/Alred/..`
Then the script is trying to access DownMedia workflow by the path and ends in `/Users/sergei.prikhodko/Google ` instead of `Google Drive`.

Well, I have rename parent Alfred folder into `Google_Drive` and then I have received two permission requests and DownMedia started to work!

There should be an issue somewhere. 
It would be nice to fix for other people ))

**Comment by vitorgalvao** [comment]
Thank you for your debugging work. That one was indeed an issue on my end. It has been fixed, so you may return the directory’s name, if you so desire. I’m glad we could get a fix in for the newest version.

> Btw, thank you for your great work! ))

Thank you for the kind words.

**Comment by vitorgalvao** [comment]
@aleksfadini If you’re using the version in this repo, you’re considerably outdated. As explained at the top of the repo, workflows here are moving to their own repos.

https://github.com/vitorgalvao/download-media-workflow/

**Comment by aleksfadini** [comment]
Thank you for calrifying, I was just looking for an issue tracker. I downloaded the version from the Alfred gallery website. I also check with the "check for workflows update" option in the workflows tab of Alfred.

Again, many thanks for the killing workflows!!!
