### ISSUE TITLE
RunCommand feature request: autocomplete shell functions/aliases

### ISSUE THREAD

**Issue by bratberg** [vitorgalvao/alfred-workflows#101]
First let me just say AWESOME WORK!

I know you probably have stuff to do, places to be, etc. but I would really love it if you added support for autocompletion/autosuggestions on custom functions and aliases from shell profile files (i.e. .zshrc). It would help me remember what commands are available as well as prevent typos :D (Maybe even show first 10 functions by default before typing the keyword, and filtering out as you enter characters?)

**Comment by vitorgalvao** [comment]
Thank you for the kind words and the interest.

For the foreseeable future I have no intention to (do the research necessary for every shell to) add the option. It would be too much work for something that is provided for free and I seldom use. Right now I can’t afford to do it.
