### ISSUE TITLE
nspasteboard.ConcealedType

### ISSUE THREAD

**Issue by appleboblin** [vitorgalvao/alfred-workflows#107]
#### Setup info

* Workflow name: StrongPassword
* Workflow version: 1.7.1
* Alfred version: 4.0.9
* macOS version: 10.15.4

#### Description of issue

Hi, I'm new to Alfred and writing workflow. I'm currently trying to convert pbcopy into nspasteboard so I can add the tag "ConcealedType" so the password generated will not be logged in Alfred clipboard history (nspasteboard.ConcealedType). I've been trying but failing as this is my first time playing around with Alfred workflow and nspasteboard. I'm wondering if you know any solutions or workarounds. New to coding in general. 
Thanks for your help and contribution!

#### Debugger output
N/A

**Comment by vitorgalvao** [comment]
For that you’ll need to use an Objective-C bridge, likely through AppleScript or JXA. To make that fit into the Workflow it would require big changes that are out of scope for its goals (it was one of the first Workflows I’ve made), though I guess I could consider a PR.

Try the [JavaScript for Automation Cookbook](https://github.com/JXA-Cookbook/JXA-Cookbook) or [Ask Different](https://apple.stackexchange.com/).
