### ISSUE TITLE
MarkdownTransform: get endless reinstalling converter message, nothing works

### ISSUE THREAD

**Issue by nikitavoloboev** [vitorgalvao/alfred-workflows#111]
#### Setup info

* Workflow name:  MarkdownTransform
* Workflow version: 20.3
* Alfred version: 4.1
* macOS version: 10.15.5

#### Description of issue

I select some text and activate it.

Here is what I get in log.

```
[01:04:55.041] STDERR: MarkdownTransform[Run Script] Ignoring redcarpet-3.5.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.5.0
/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A4C9B6F5-B1B9-4B49-AC24-C13F11C295C0/ensure_redcarpet.rb:15:in `rescue in <top (required)>': uninitialized constant Redcarpet_dir (NameError)
	from /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A4C9B6F5-B1B9-4B49-AC24-C13F11C295C0/ensure_redcarpet.rb:9:in `<top (required)>'
	from ./bbcode:3:in `require_relative'
	from ./bbcode:3:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- redcarpet (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A4C9B6F5-B1B9-4B49-AC24-C13F11C295C0/ensure_redcarpet.rb:10:in `<top (required)>'
	from ./bbcode:3:in `require_relative'
	from ./bbcode:3:in `<main>'
[01:04:55.042] MarkdownTransform[Run Script] Processing complete
[01:04:55.042] MarkdownTransform[Run Script] Passing output '' to Copy to Clipboard
[01:04:55.043] MarkdownTransform[Copy to Clipboard] Processing complete
[01:04:55.043] MarkdownTransform[Copy to Clipboard] Passing output '' to Run Script
```

**Comment by vitorgalvao** [comment]
Just released a new version. Try that.

**Comment by nikitavoloboev** [comment]
Ok it works but first it gives this error every time.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/6391776/85643887-bddd4a00-b695-11ea-8971-94f67eea6fc4.png">

I know it's solved by right clicking on binary but not sure where it is found.

**Comment by vitorgalvao** [comment]
It’s right at the root of the directory.

**Comment by nikitavoloboev** [comment]
Thx. One small issue don't want to open new issue for but for some reason, the transform adds many spaces.

From this.


[Hello](https://github.com/vitorgalvao/alfred-workflows/issues/111)

<img width="772" alt="image" src="https://user-images.githubusercontent.com/6391776/85644407-1eb95200-b697-11ea-96ff-a00aaa239170.png">

When I activate, it turns to:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/6391776/85644425-2ed13180-b697-11ea-8429-9f9e312851f1.png">

I hope you can replicate it. I can replicate it 100% of the time.

**Comment by vitorgalvao** [comment]
That’s by design. It’s specifically to circumvent oddities from IPBoard, which the Alfred forum runs on.
