### ISSUE TITLE
Changing downloads_dir env variable causes workflow to stop working

### ISSUE THREAD

**Issue by modermo** [vitorgalvao/alfred-workflows#117]
#### Setup info

* Workflow name: RecentDownloads
* Workflow version: 20.6
* Alfred version: v4.1.1
* macOS version: 10.15.6

#### Description of issue

I love the functionality of this workflow and was hoping to apply it to other folders as well. So, I tried duplicating the workflow, changing the workflow shortcut (so as not to conflict with the others) and changing the environment variable `downloads_dir` to `~/Desktop` but I keep getting the below result upon execution of the shortcut.

#### Debugger output

```
12:14:10.003] ERROR: RecentScreenshots[Script Filter] Code 1: ./recentdownloads:35:in `initialize': no implicit conversion of nil into String (TypeError)
	from ./recentdownloads:35:in `Pathname'
	from ./recentdownloads:35:in `<main>'
```

**Comment by vitorgalvao** [comment]
Double click the Workflow’s name on the Workflow list and fill the `Bundle Id` line.

Bundle IDs are meant to be unique, so duplicating a Workflow makes it blank. That ID is also used to determine the Workflow’s cache and data directories, so because it is blank they don’t exist.

**Comment by vitorgalvao** [comment]
Thank you for making a clear bug report. It made it straightforward for me to find the culprit.

**Comment by modermo** [comment]
The Bundle ID does actually fix the crashing issue, but typing in the new shortcut for the duplicated workflow still opens the Downloads path even after changing the `downloads_dir` variable to something like `~/Desktop`.

Do I need to "refresh" the workflow? I tried exporting and reimporting, but it still opens the Downloads directory.

**Comment by vitorgalvao** [comment]
> but typing in the new shortcut for the duplicated workflow still opens the Downloads path even after changing the `downloads_dir` variable to something like `~/Desktop`.

I’m not able to reproduce that.

**Comment by modermo** [comment]
Duplicate the workflow and then change the `downloads_dir` to another path. Is it opening your new path?

**Comment by vitorgalvao** [comment]
Download the latest version, just released.

**Comment by modermo** [comment]
That fixes it! Thanks so much for the amazing speed at which you turned the fix around. This is a brilliant workflow!
