### ISSUE TITLE
UploadFile new host suggestion and code for it

### ISSUE THREAD

**Issue by AnthoPakPak** [vitorgalvao/alfred-workflows#120]
Hey,

Thanks a lot for the UploadFile workflow that I'm using for months! Over the months, hosts support has changed because of some being abandoned. My preferred one was transfer.sh for its simplicity and not having ads. Unfortunately it's one of those that have been removed. You've recently added 0x0.st which is pretty great. The only issue I have with it is that it renames the uploaded files to something random. Which in some cases can be confusing for the downloader.

I've recently found https://arxius.io/ host. It supports all file types, doesn't have ads, and doesn't rename files. I think it's a pretty good one!

I've managed to add support for it in your workflow with following curl command:
`curl --globoff --progress-bar --form "file=@\"${escaped_file_path}\"" "https://arxius.io" 2> "${progress_file}" | tr -d '\n' | pbcopy`

It works smoothly. I'm sharing the code with you so that you and others can profit from this.
I'm opening an issue instead of making a PR because I guess you'll make other changes on your side (workflow version, …).

Thanks again for your work! ✌️

**Comment by vitorgalvao** [comment]
> My preferred one was transfer.sh for its simplicity and not having ads.

Mine as well. Though they’ve been unreliable for a long time before being discontinued.

> You've recently added 0x0.st which is pretty great. The only issue I have with it is that it renames the uploaded files to something random.

Worse: it’s sequential, meaning they are possibly guessable. And [extensions have a length limit](https://github.com/mia-0/0x0/issues/23).

> I've recently found https://arxius.io/ host.

Nice find! Though they keep files indefinitely, which I also find to be a problem, so the search for the perfect host continues. Still, I’ve added it to the Workflow, it’s just not the default.

Thank you for the recommendation. If you find more, I’d be interested to keep adding them!

**Comment by AnthoPakPak** [comment]
I wasn't aware of those other limitations with 0x0.st.
Yeah, files are kept indefinitely with Arxius… When having an account we can delete them, but unfortunately I don't think we can upload with curl while being logged in 😕
Though, I'm glad you've added it to the workflow, this is probably the one I'll use for now. I'll be able to keep auto updates 😊

**Comment by AnthoPakPak** [comment]
Unfortunately the uploading is broken since a few days on arxius.io, and after contacting the dev he told me they'll soon shutdown the website.

By chance, it seems that transfer.sh is back, hopefully it will last! 🤞

@vitorgalvao Guess you can remove Arxius support… 😕

**Comment by vitorgalvao** [comment]
Thank you for checking. Updated the Workflow.
