### ISSUE TITLE
MarkdownTransform fails if workflow dir path has space in it

### ISSUE THREAD

**Issue by mr-pennyworth** [vitorgalvao/alfred-workflows#127]
#### Setup info

* Workflow name: MarkdownTransform
* Workflow version: 21.5
* Alfred version: 4.3.4
* macOS version: 10.15.7
* Architecture: Intel

#### Description of issue
MarkdownTransform fails if `ENV['multimarkdown_bin']` has space in it
Workflow Dir: `/Volumes/Cloud/GoogleDrive/Alfred Preferences/Alfred.alfredpreferences/workflows/user.workflow.4F63373B-C042-43F1-9204-9AB665A414FA`
Note the space in `Alfred Preferences`

#### Debugger output

```
[11:31:49.219] MarkdownTransform[Hotkey] Passing output 'Hello' to Run Script
[11:31:49.349] STDERR: MarkdownTransform[Run Script] /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `spawn': No such file or directory - /Volumes/Cloud/GoogleDrive/Alfred (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:159:in `popen2'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:342:in `capture2'
	from ./bbcode:13:in `<main>'
[11:31:49.353] MarkdownTransform[Run Script] Processing complete
```

**Comment by vitorgalvao** [comment]
Closed by https://github.com/vitorgalvao/alfred-workflows/pull/128.

By the way, in my book, you can forego the issue if you intend to submit a PR anyway.

**Comment by mr-pennyworth** [comment]
> By the way, in my book, you can forego the issue if you intend to submit a PR anyway.

That makes sense! :)
