### ISSUE TITLE
DownMedia for Raycast

### ISSUE THREAD

**Issue by kapnod** [vitorgalvao/alfred-workflows#132]
Hi. Is it possible to do Script Commands DownMedia for the Raycast application? 

[Raycast](https://raycast.com) is like Alfred only more modern and interesting.
It would be cool if the DownMedia process was also available for Raycast.

Here is the documentation and examples of Script Commands for Raycast - 
https://github.com/raycast/script-commands
https://github.com/raycast/script-commands/tree/master/commands

**Comment by vitorgalvao** [comment]
> [Raycast](https://raycast.com) is like Alfred only more modern and interesting.

It’s newer, not “more modern”. “More interesting” is highly debatable. What it has is hype backed up by money. From what I’ve seen, Raycast is less powerful and expressive than Alfred; I don’t see anything that would be worth the switch, especially to a VC-funded startup which I expect will either be sold with abandon or go bust.

I make and distribute these Workflows for free, at the expense of my time. I have no desire to rewrite for free such a complex Workflow to a less capable alternative I don’t use.
