### ISSUE TITLE
QuitArena failing to quit apps

### ISSUE THREAD

**Issue by volt4ire** [vitorgalvao/alfred-workflows#133]
#### Setup info

* Workflow name: QuitArena
* Workflow version: 21.1
* Alfred version: 4.3.4
* macOS version: 11.4
* Architecture: Intel

#### Description of issue

Oftentimes QuitArena fails to quit any programs when invoked. I am running the latest version of Alfred, QuitArena, and macOS. Can you please help me diagnose this? Thanks for your time and all your awesome workflows!!

#### Debugger output

```
[09:15:26.933] Logging Started...
[09:16:11.063] QuitArena[Keyword] Processing complete
[09:16:11.068] QuitArena[Keyword] Passing output '' to Run Script
[09:16:11.585] ERROR: QuitArena[Run Script] /Users/rwbarat/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/DAE9F815-4429-4B6B-9757-8DD715459650: execution error: Error: Error: User canceled. (-128)
[09:16:11.591] QuitArena[Run Script] Processing complete
[09:16:11.592] QuitArena[Run Script] Passing output '' to Run Script
```

**Comment by vitorgalvao** [comment]
Thank you for the kind words.

> execution error: Error: Error: User canceled. (-128)

Any idea what happened there?

What are your values for the Workflow Environment Variables? How are you invoking QuitArena?

**Comment by volt4ire** [comment]
Thanks for your help!
> Any idea what happened there?

I'm not sure what is causing this

> What are your values for the Workflow Environment Variables? How are you invoking QuitArena?

I'm invoking it through the keyword ("qapps") and these are my environment variables: 
![image](https://user-images.githubusercontent.com/8772017/123432304-3c661380-d598-11eb-8ba9-c5c8b38fcd0d.png)

**Comment by vitorgalvao** [comment]
Unfortunately, that doesn’t give us more details. The fact it only happens sometimes and you’re the only one experiencing this suggests it’s something in your setup.

Due to the error message, I’d say one the apps may have unsaved changes and is thus refusing to quit. Like I say in the README:

> Note both options *ask* the apps to exit (`SIGTERM`) instead of *telling* them (`SIGKILL`). If you need to force individual processes to terminate, use [ProcessControl](https://github.com/vitorgalvao/alfred-workflows/tree/master/ProcessControl) instead.

So I’d start by looking into that next time it happens. If you can find a way to reproduce the problem reliably and it is indeed a bug, let me know and I’ll reopen.
