### ISSUE TITLE
How does WebScreenshot workflow upload work ?

### ISSUE THREAD

**Issue by akharrou** [vitorgalvao/alfred-workflows#138]
Hello,

Regarding the `WebScreenshot` workflow, just curious under/unto whose account is the image uploaded ? Or if I'm not understanding something, how does it work ? Also are there limits as to the duration that the image is hosted ?

Thanks for posting your amazing workflows, they're super useful !

**Comment by vitorgalvao** [comment]
> under/unto whose account is the image uploaded ?

No one’s, it’s an anonymous post. You can also do those from the web interface.

> Also are there limits as to the duration that the image is hosted ?

Not that I’m aware. I’ve been using it to host images I embed in Workflows for years and never had an issue.

> Thanks for posting your amazing workflows, they're super useful !

Thank you for the kind words!
