### ISSUE TITLE
The workflow does not work.

### ISSUE THREAD

**Issue by chumido98** [vitorgalvao/alfred-workflows#139]
#### Setup info

* Workflow name: UploadFile
* Workflow version: v21.6
* Alfred version: 4.6.1[1272]
* macOS version: MacOS Monterey 12.0.1
* Architecture: Intel

#### Description of issue

It's just does not work. Can you help me, sir?

![CleanShot 2021-11-24 at 14 58 27@2x](https://user-images.githubusercontent.com/61721378/143198038-a734a394-3df0-4e6f-9e0a-3b95e5c44c94.png)

<img width="620" alt="CleanShot 2021-11-24 at 14 58 59@2x" src="https://user-images.githubusercontent.com/61721378/143198078-15b48a15-0810-44c9-a6d6-d3fe9add3403.png">

![CleanShot 2021-11-24 at 14 59 49@2x](https://user-images.githubusercontent.com/61721378/143198094-67089f74-3431-4c66-9ae4-dbd76989df08.png)

**Comment by vitorgalvao** [comment]
“Does not work” doesn’t give enough information to find an issue.

You deleted the most important part of the template. I need the debugger output.

**Comment by chumido98** [comment]
> “Does not work” doesn’t give enough information to find an issue. It works for me and other users. Your screenshots suggest that it is working for you as well.
> 
> You deleted the most important part of the template. I need the debugger output. I also need to know what you did and what you expected.

Sorry for not describe enough information.
I installed the lastest version --> I tried to upload a image --> There a noti said that tt\he image is uploading --> I check the progress but don't see the percent progress text --> There a noti said that the image uploaded --> I checked the clipboard but don't see any link in it.

Sorry for my bad English

**Comment by vitorgalvao** [comment]
Again, if you don’t give me the debugger output I can’t help you.

**Comment by chumido98** [comment]
> Again, if you don’t give me the debugger output I can’t help you.

I found the problem. My bad. I use Lulu, and it block the internet come out. It work again. Thanks for your time.
