### ISSUE TITLE
StartRecording does not work on Monterey

### ISSUE THREAD

**Issue by Artem-Sukhliak-Funzy** [vitorgalvao/alfred-workflows#140]
#### Setup info

* Workflow name: StartRecording
* Workflow version: v20.1
* Alfred version: Alfred 4.6, Build 1266, Friday 15th October 2021
* macOS version: 12.0.1 (21A559)
* Architecture: Intel

#### Description of issue

On previous MacOS it worked. Right now after typing workflow in Alfred - nothing happens. It just does not start

#### Debugger output

```
11:07:36.265] Logging Started...
[11:07:45.716] StartRecording[Keyword] Processing complete
[11:07:45.717] StartRecording[Keyword] Passing output '' to Arg and Vars
[11:07:45.718] StartRecording[Arg and Vars] Processing complete
[11:07:45.718] StartRecording[Arg and Vars] Passing output 'webcam' to Run Script
[11:07:47.131] StartRecording[Run Script] Processing complete
[11:07:47.134] StartRecording[Run Script] Passing output 'true
' to Run Script
```

**Comment by vitorgalvao** [comment]
Can’t reproduce, works fine for me.

Check System Preferences → Security & Privacy → Privacy → Automation. Make sure `QuickTime Player.app` is checked under `Alfred 4.app`.

**Comment by Artem-Sukhliak-Funzy** [comment]
`QuickTime Player.app` is enabled under `Alfred 4.app`.

To make sure, are you saying that when you type "recordXXX" you launching QuickTime player with already enabled tool to select area to record?

**Comment by vitorgalvao** [comment]
> To make sure, are you saying that when you type "recordXXX" you launching QuickTime player with already enabled tool to select area to record?

Yes, [as the instructions say](https://github.com/vitorgalvao/alfred-workflows/blob/master/StartRecording/README.md). How have you been using the Workflow in previous macOS versions without noticing that? You have to interact with QuickTime Player to keep whatever you recorded.

**Comment by Artem-Sukhliak-Funzy** [comment]
Before, after typing "RecordXXX", QuickTime Player always opened with auto-activated "select recording area" tool

**Comment by vitorgalvao** [comment]
Whatever it activates depends on whatever you choose to record. In you report you were recording the webcam, and that doesn’t require an area selection.

Either way, I can’t reproduce and no one else has reported this. This is almost certainly a permissions issue, but definitely a problem in your macOS setup. You’ll have to find what that is.
