### ISSUE TITLE
See Download queue

### ISSUE THREAD

**Issue by Paul-creator** [vitorgalvao/alfred-workflows#141]
#### Setup info

* Workflow name: DownMedia
* Workflow version: 21.11
* Alfred version: 4.6.1
* macOS version: 12.0.1
* Architecture: Apple Silicon

It would be really useful if there were a visible download queue, where you can also push any item to the top of the queue (download that one instead of the current download) and remove any item from the queue.

**Comment by vitorgalvao** [comment]
I definitely see the value in it, but I’ve been mulling on it the past few days and remain unconvinced it’s worth the extra effort. This would be useful too sparingly, considering there is already `dp`. You can’t see all downloads in waiting, but if you know you have something to prioritise you can already <kbd>⌘</kbd><kbd>↵</kbd> to send the current one to the back.

The current method takes advance of Alfred’s `running instances` which ensures things don’t trample over each other. Implementing what you ask would require creating a whole bespoke queuing system which is another entry point for bugs.

I started this post thinking “maybe” but in the course of writing it decided it’s not something I want to pursue. It’s all downside and zero upside for me; I can’t justify the commitment.

**Comment by vitorgalvao** [comment]
Thank you anyway for the feature request.
