### ISSUE TITLE
DownMedia not responding

### ISSUE THREAD

**Issue by mlarrubia** [vitorgalvao/alfred-workflows#143]
#### Setup info

* Workflow name: Downmedia
* Workflow version: 
* Alfred version: 4
* macOS version: Monterey 12.1 
* Architecture: (Intel or Apple Silicon) M1 Max

#### Description of issue

My issue is pretty vague. I downloaded "DownMedia" from http://www.packal.org/workflow/downmedia
Once i open it it gets picked up by Alfred and is located in "Workflows" 
Like all other workflows I can now use Alfred to run the command so i fire up Alfred and type "dv" or "da" while the video is in my foremost browser (Active tab) 

The issue is that unlike all the other workflows "DownMedia" isn't even recognized in the Alfred spotlight terminal. There is nothing populating when i type "dv" or "da" 

#### Debugger output

```
No output. 
This is the meta data on DownMedia

{
  "alfredworkflow" : {
    "category" : "",
    "readme" : "The canonical source for all my Workflows is their github repository: https:\/\/github.com\/vitorgalvao\/alfred-workflows. That is their home for downloads and instructions.\n\nI’m only keeping rectifying copies — such as this one — on Packal. You’ll find a single trigger in it: `update`. It will download and install the latest version of the correct Workflow, replacing this placeholder.\n\nThe downloaded Workflow will keep itself updated with `OneUpdater`: https:\/\/github.com\/vitorgalvao\/alfred-workflows\/tree\/master\/OneUpdater",
    "createdby" : "Vítor Galvão",
    "downloadurl" : "",
    "version" : "0.0.0",
    "bundleid" : "com.vitorgalvao.alfred.downmedia",
    "description" : "Download and install the latest version of DownMedia",
    "name" : "DownMedia",
    "webaddress" : "http:\/\/vitorgalvao.com\/"
  }
}
```

**Comment by mlarrubia** [comment]
I was able to solve it by using alfred and typing update. IDK why or how.

**Comment by vitorgalvao** [comment]
The debugger output pretty much explains it. Don’t use Packal; it’s a zombie breaking down andI don’t link to it anywhere. All my Workflow on it are just stubs which update to the real versions.
