### ISSUE TITLE
Add feature to override preserving extension for RenameAction

### ISSUE THREAD

**Issue by nmajin** [vitorgalvao/alfred-workflows#150]
No bug but curious if we can provide a parameter to override preserving the extension for `RenameAction`? I would actually like to control the entire naming of the file (i.e. appending maybe a .txt or .whatever to the file).

**Comment by vitorgalvao** [comment]
It’s something I’ve considered before but that I don’t intend to add at this time. It’s a rare need and would complicate the code, for something I want to make sure works safely.

Thank you anyway for the feature request.
