### ISSUE TITLE
WatchList: option to 'not Trash' after watching

### ISSUE THREAD

**Issue by notDavid** [vitorgalvao/alfred-workflows#151]
Hi there,

please consider implementing an option to not delete files to the Trash after watching them, if desired.
(I often want to keep the files i watch, and would prefer to remove them manually when needed.)

Thank you for creating the great workflow(s)!

**Comment by vitorgalvao** [comment]
[Done.](https://www.alfredforum.com/topic/1931-watchlist-—-play-and-manage-local-audiovisual-content-and-streams/page/4/#comment-94676)

**Comment by notDavid** [comment]
Thank you so much!
