### ISSUE TITLE
ANU QRNG is currently down

### ISSUE THREAD

**Issue by carceneaux** [vitorgalvao/alfred-workflows#157]
#### Setup info

* Workflow name: StrongPassword
* Workflow version: 22.4
* Alfred version: 5.0.1 [2067]
* macOS version: 12.5
* Architecture: Intel

#### Description of issue

Workflow depends on ANU QRNG (https://qrng.anu.edu.au) and it is currently down which causes the workflow to hang and never complete.

I recognize the source of the issue isn't necessarily this workflow but I raised this issue so others were aware.

Recommendations:

* Add a secondary method for retrieving a random alphanumeric string in case primary method is unavailable
* Add error checking so error is displayed instead of workflow hanging at `Run Script` step

**Comment by vitorgalvao** [comment]
Thank you for the report. Updated the Workflow to add random.org.

![](https://i.imgur.com/QkwVwPp.png)
