### ISSUE TITLE
Support for MacPorts PATH

### ISSUE THREAD

**Issue by mariusdkm** [vitorgalvao/alfred-workflows#160]
Currently Alfred doesn't include the default path of mac ports binaries in it's PATH variable.
So it would be great to add support for that in your scripts when using external binaries, 
specifically in my case `yt-dlp` the DownMedia workflow.

My current workaround is just to add `ENV['PATH'] = '/opt/local/bin:/opt/local/sbin:' + ENV['PATH']` 
at the beginning of the `downmedia_functions.rb` file. (If this is considered ok, I could also open a PR)

**Comment by vitorgalvao** [comment]
Thank you for the request but I only support installations via Homebrew. In a literal decade of developing workflows, this is the first time I remember someone asking for MacPorts support.

You can add a `PATH` Workflow Environment Variable to the workflow but I would recommend instead symlinking the binary to `/usr/local/bin`.
