### ISSUE TITLE
Bug alfred-workflows

### ISSUE THREAD

**Issue by Romaric-EMBA** [vitorgalvao/alfred-workflows#163]
#### Setup info

* Workflow name: Notion Search
* Workflow version: v.0.5.1-alfred5
* Alfred version: 5.05
* macOS version: 13.0.1
* Architecture: (Intel or Apple Silicon) Intel

#### Description of issue

Hello Vitor,

I used 3 browsers Chrome firefox and safari
and didn't find "spaceId" so I used "notion_user_ id"
I found "notion_browser_id" for cookie

I put those data in "configure workflow" as requested and in [x] in respective defalt value

The workflow doesn't work

Can you tell me where I made a mistake

Thank you

Best regards,

Romaric

![Screenshot 2022-12-03 at 21 26 11](https://user-images.githubusercontent.com/40163778/205461040-7ea3cee6-fa48-44d9-91a0-4849411bc033.jpg)
![Screenshot 2022-12-03 at 21 26 31](https://user-images.githubusercontent.com/40163778/205461046-c9d81bbd-1a15-4bea-9c4a-e3223ed9c077.jpg)

#### Debugger output

```
Open the [debugger](http://support.alfredapp.com/workflows:debugger), set the log output to “All Information”, and post the output here, replacing this text but keeping the backticks.
```

**Comment by vitorgalvao** [comment]
I’m not the author of that workflow. You’ll have to ask its creator.
