### ISSUE TITLE
Temporary Email: Can it work with firefox?

### ISSUE THREAD

**Issue by juan9999** [vitorgalvao/alfred-workflows#167]
#### Setup info

* Workflow name:Temporary Email
* Workflow version:Latest
* Alfred version:4
* macOS version:13.1
* Architecture: Apple Silicon

#### Description of issue

Works fine in Safari but not firefox

#### Debugger output

```
Open the [debugger](http://support.alfredapp.com/workflows:debugger), set the log output to “All Information”, and post the output here, replacing this text but keeping the backticks.
```

**Comment by vitorgalvao** [comment]
Firefox isn’t supported because they don’t support AppleScript.

**Comment by juan9999** [comment]
Thanks for the quick response.

It would be great in the read.me to include a list of supported browsers and maybe a note that firefox doesn’t support AppleScript so it won’t work. Tried it with Orion too and no luck.

**Comment by vitorgalvao** [comment]
Orion too doesn’t have good AppleScript support, though in their case it’s a “yet”, they’re working on it.

The workflow works in all major browsers and it’s known that Firefox doesn’t support AppleScript (the bug report for it has been open for over two decades). Listing every supported browser in every workflow would would be repetitive and become outdated as browsers come and go, and it’s important to note the browsers themselves are where the support is lacking. As they add it, I'll gladly support them too.
