### ISSUE TITLE
TemporaryEmail: Support for Arc Browser

### ISSUE THREAD

**Issue by AnthoPakPak** [vitorgalvao/alfred-workflows#168]
I've modified the workflow to support Arc Browser. You might be interested in updating it for other users (I don't think PRs are doable for Alfred Workflows).

Here's the Apple Script to open a new tab with passed url: `osascript -e "tell application \"Arc\" to tell the active space of front window to make new tab with properties {URL:\"${url}\"}"`.
The set active tab part isn't required for Arc since it automatically switches to the newly opened tab.

Which results in this script:
```
function notification {
  ./notificator --message "${1}" --title "${alfred_workflow_name}"
}

readonly email_name="${1//[^[:alnum:]]}"

if [[ "${service}" == 'harakirimail.com' ]]; then
  readonly email="${email_name}@harakirimail.com"
  readonly url="https://harakirimail.com/inbox/${email_name}"
elif [[ "${service}" == 'maildrop.cc' ]]; then
  readonly email="${email_name}@maildrop.cc"
  readonly url="https://maildrop.cc/inbox/${email_name}"
else
  readonly email="${email_name}@guerrillamail.com"
  readonly url="https://guerrillamail.com/inbox/${email_name}"
fi

readonly front_browser="$(osascript -e 'tell application "System Events" to return name of first process whose frontmost is true')"

if [[ "${front_browser}" == 'Safari'* || "${front_browser}" == 'Webkit'* ]]; then
  osascript -e "
    tell application \"${front_browser}\" to tell front window
      set tabIndex to index of current tab
      make new tab at after tab tabIndex with properties {URL:\"${url}\"}
    end tell
  "  > /dev/null
elif [[ "${front_browser}" == 'Google Chrome'* || "${front_browser}" == 'Chromium'* || "${front_browser}" == 'Opera'* || "${front_browser}" == 'Vivaldi'* || "${front_browser}" == 'Brave Browser'* || "${front_browser}" == 'Microsoft Edge'* ]]; then
  osascript -e "
    tell application \"${front_browser}\" to tell front window
      set tabIndex to active tab index
      make new tab at after tab tabIndex with properties {URL:\"${url}\"}
      set active tab index to tabIndex
    end tell
  "
elif [[ "${front_browser}" == 'Arc'* ]]; then
	osascript -e "tell application \"Arc\" to tell the active space of front window to make new tab with properties {URL:\"${url}\"}"
else
  notification 'You need a supported browser as your frontmost app'
  exit 1
fi

echo -n "${email}"
notification 'Temporary email address copied to clipboard'
```

**Comment by AnthoPakPak** [comment]
Thanks for your answer! To be honest, I was expecting Arc to be using Chromium Apple Script, and was surprised it doesn't. I'll suggest this to the Arc team, since for easier adoption, I agree it's a good idea to keep up with the existing Chromium dictionary.

I didn't knew your workflows now have their own repositories, thanks for letting me know.

(Btw, I can send you an invite if it's a matter of being able to test it)

**Comment by vitorgalvao** [comment]
> I can send you an invite if it's a matter of being able to test it

That’s probably a good idea, thank you. It will allow me to look at it sooner. What information do you need? Assuming an email: plats.advised_0j@icloud.com

**Comment by AnthoPakPak** [comment]
I've just sent you the invite. If you try it enough, you'll probably won't look back at Chrome anymore 😉

**Comment by vitorgalvao** [comment]
I’ll add support for Arc in an update later today. Worth noting Arc has no support for tab indexes in AppleScript, meaning that unlike other browsers it won’t be possible to open the tab in the background and return to the current tab.

**Comment by jarjumarvin** [comment]
> I’ll add support for Arc in an update later today. Worth noting Arc has no support for tab indexes in AppleScript, meaning that unlike other browsers it won’t be possible to open the tab in the background and return to the current tab.

Hey Vítor, did you end up working on this any further? Thank you :)
