### ISSUE TITLE
Arc Browser compatibility

### ISSUE THREAD

**Issue by DSGND** [vitorgalvao/alfred-workflows#170]
https://github.com/vitorgalvao/alfred-workflows/blob/e9255e5ba9768fbd33401e895493f70f1d953b92/IncognitoClone/source/info.plist#L270

I've added 'Arc' in the Array, but it just open a new empty window, based on the previous space.

Arc Browser has this user agent "[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36]" and / or may have tweaked its "Chromium" incognito mode… :/

**Comment by vitorgalvao** [comment]
The user agent is not relevant, Arc uses different AppleScript from other Chromium browsers. [Supporting it or not is under consideration](https://github.com/vitorgalvao/alfred-workflows/issues/168#issuecomment-1419371180).

**Comment by DSGND** [comment]
Hi Vitor,

Thanks for your quick answer. It's clear for me. No problem for the futur Arc support, or not :)

Good job anyway for all your Alfred Workflow, especially 1Password ! It's a life changer for me for years !

**Comment by vitorgalvao** [comment]
Thank you for the kind words. Have a great week.
