### ISSUE TITLE
MachineClean does not work on the MacBook Air

### ISSUE THREAD

**Issue by vitorgalvao** [vitorgalvao/alfred-workflows#19]
Opening and closing this issue for reference.

If you’ve come here, there’s a good chance you tried to open [MachineClean](https://github.com/vitorgalvao/alfred-workflows#machineclean) on a MacBook Air. Unfortunately, this workflow does not work reliably on that particular laptop, an no one affected has yet figured out why. Most notably, the last issue on this at the time of writing was #13.

On some models the workflow simply does not work, while on others it can may not release the lock, meaning you’ll have to restart to get your computer back to normal. This has been confirmed on some 2013, 2014, and 2015 models.

If you have a solution to the problem or wish to try this workflow on your particular model, please open a new issue and reference this one.

**Comment by GandalfSaxe** [comment]
I'm getting forwarded to this issue now. It worked until very recently (could be the latest review, could be that I'm on Catalina beta).

**Comment by vitorgalvao** [comment]
As I’ve mentioned at the top:

> If you have a solution that reliably works on any model, please do let me know.

Otherwise, I’m not going to work on this problem anymore. This issue is purely informational.

There are apps that can lock the keyboard — I think by essentially registering all keys to do nothing — but they all require a GUI. I have thoughts on how a CLI-only tool could work and have discussed early ideas with someone months ago, but she hasn’t gotten the chance to work on it.

If you’re a Swift or Objective-C developer and think you could do it, let’s talk. Otherwise, this will remain unchanged until the day I can do it on my own or give up on it.

**Comment by vitorgalvao** [comment]
A small update, because I’ve gotten a reply on this issue. As I’ve mentioned at the top:

> If you have a solution that reliably works on any model, please do let me know.

Otherwise, I’m not going to work on this problem anymore. This issue is purely informational.

There are apps that can lock the keyboard — I think by essentially registering all keys to do nothing — but they all require a GUI. I have thoughts on how a CLI-only tool could work and have discussed early ideas with someone months ago, but she hasn’t gotten the chance to work on it.

If you’re a Swift or Objective-C developer and think you could do it, let’s talk (open a new issue or contact me another way you prefer). Otherwise, this will remain unchanged until the day I can do it on my own or give up on it.
