### ISSUE TITLE
Nothing happens after initiating (OSX)

### ISSUE THREAD

**Issue by callumflack** [vitorgalvao/alfred-workflows#21]
LabelColor isn't giving me anything when initiated. Sorry I can't be more helpful than that, my knowhow w/ Alfred workflows is zero.

Updated, deleted and reinstalled on OSX 10.11.5 from your Github link, no difference made.

**Comment by vitorgalvao** [comment]
> Sorry I can't be more helpful than that

Sure you can (and you need to, for me to be able to help you). *How* are you calling it, and what Alfred version are you using?

**Comment by vitorgalvao** [comment]
ItLs likely you’re using Alfred 3, hence why it isn’t working. I had already updated it, but not released it. Download the latest version now, and it should work.

**Comment by callumflack** [comment]
Thanks @vitorgalvao. Calling it via a file search hotkey. Yes I'm using Alfred 3 and yes, your latest version works.
