### ISSUE TITLE
Feature Request - View (instead of replace) the correct spelling

### ISSUE THREAD

**Issue by jovobe** [vitorgalvao/alfred-workflows#27]
It would be nice if one can type something like "spell ralley" and the workflow shows up "rallye" (without replacing in). The current workflow uses the spell command from alfred which does not work for other languages than english (e.g. german).

**Comment by vitorgalvao** [comment]
> The current workflow uses the spell command from alfred which does not work for other languages than english (e.g. german).

It does. It uses whatever dictionaries you have in Dictionary.app. Add your language there, and Alfred’s `spell` will use it as well.

**Comment by jovobe** [comment]
Thanks, but it doesn't work the way I described it in german. For english the spelling seems to be very good but for german not. The replace feature from your workflow though works like a charm for german. Is it possible to use the service (service.afterthedeadline.com) for the preview feature as well? (and not only for the inline replace thing)

**Comment by vitorgalvao** [comment]
> For english the spelling seems to be very good but for german not.

That is something you should likely [report to Apple](https://bugreport.apple.com).

> Is it possible to use the service (service.afterthedeadline.com) for the preview feature as well?

Yes, but I won’t do it. I’ve added that feature to the workflow but don’t really use it and don’t see neither enough value nor enough demand (you’re the only one) to justify the work. I already have too much free open-source work on my hands right now.

**Comment by jovobe** [comment]
> Yes, but I won’t do it. I’ve added that feature to the workflow but don’t really use it and don’t see neither enough value nor enough demand (you’re the only one) to justify the work. I already have too much free open-source work on my hands right now.
Alright, i'm going to implement it myself. Thanks for Your time :)

**Comment by vitorgalvao** [comment]
> Thanks for Your time

Thank you for taking the time to open the issue and make the request.
