### ISSUE TITLE
LinkClean: not working, Alfred 3 compatibility issue?

### ISSUE THREAD

**Issue by lrobeson** [vitorgalvao/alfred-workflows#28]
Is this compatible with Alfred 3.2.1? If so, does it need some kind of extra config?

- I copied a long link from Amazon (https://www.amazon.com/Rocco-Roxie-Gourmet-Jerky-Treats/dp/B00H2ZS5VM/ref=sr_1_4?s=pet-supplies&ie=UTF8&qid=1482944944&sr=1-4&keywords=dog+treats+made+in+usa)
- did 'lc'
- got back the same long URL

**Comment by vitorgalvao** [comment]
Nothing to do with Alfred’s version, the workflow just wasn’t handling specific `ref=` cases from Amazon, as those aren’t preceded by `?` or `&`, like other sites.

Updated the workflow to handle those, just download the newest version and you’re good to go.

**Comment by lrobeson** [comment]
Perfect! Thanks so much for the quick fix and great workflow!
