### ISSUE TITLE
MachineClean stopped working on Alfred 2

### ISSUE THREAD

**Issue by rEes9P** [vitorgalvao/alfred-workflows#29]
I loved MachineClean but it suddenly stopped working for me. I am on macOS 10.11.6 and using Alfred 2 v2.8.7. I'd greatly appreciate your help in bringing MachineClean back to life!

**Comment by vitorgalvao** [comment]
Try [this link](https://github.com/packal/repository/raw/efc5a30879b0ae27a8f6e7f77cf269876cf2eaa9/com.vitorgalvao.alfred.machineclean/machineclean.alfredworkflow).

That’s an old one, and keep in mind it’s no longer supported. Alfred 3 can’t save Alfred 2 links and the newest versions of MachineClean have features unsupported by Alfred 2 anyway.

**Comment by rEes9P** [comment]
Thanks for this, @vitorgalvao, but it doesn't seem to work. Nothing happens. Tried to look up the debug log but all it says is "Starting debug for 'MachineClean'".

**Comment by vitorgalvao** [comment]
@rEes9P Unfortunately, I won’t spend any time debugging the issue.

As I mentioned, that’s an old unsupported version. Search the issues and you’ll see how much of a headache it is to debug that workflow, as it may stop working for a number of reasons, including the type of your machine.

I may try to debug it in cases where I have any clues and it is using the latest version, but in your case I’d just be shooting in the dark, and I’ve already wasted too much of my free time debugging that specific workflow for other people.

I simply cannot afford to put more of my time into that particular problem.

**Comment by rEes9P** [comment]
No worries, @vitorgalvao, I've been meaning to update to Alfred 3 anyways so will get the latest version of Machine Clean when I do. Thanks for a nifty utility and for all your time in developing and supporting it!

**Comment by vitorgalvao** [comment]
@rEes9P Thank you for the kind words and for understanding. Too many users would instead have lashed out.
