### ISSUE TITLE
I think it didn't work

### ISSUE THREAD

**Issue by KittenYang** [vitorgalvao/alfred-workflows#30]
In my mac,it requires password everytime and after I input password it still can use keyboard or trackpad.I just change the environment variables `seconds_to_lock` and do nothing else.

**Comment by vitorgalvao** [comment]
> it requires password everytime

That’s as designed.

See [other issues related to MachineClean](https://github.com/vitorgalvao/alfred-workflows/issues?q=is%3Aissue+is%3Aclosed+label%3AMachineClean). [As I said before](https://github.com/vitorgalvao/alfred-workflows/issues/29#issuecomment-274256653) (emphasis added):

> I may try to debug it in cases where I have any clues and it is using the latest version, but in your case I’d just be shooting in the dark, and I’ve already wasted too much of my free time debugging that specific workflow for other people.
>
> I simply cannot afford to put more of my time into that particular problem.

MachineClean is using unconventional methods for locking, and it’s incredibly machine dependent. For example, it does not work on Macbook Airs and no one yet has been able to figure out why. If you can provide any clues, I’ll look into it, but I won’t spend more time shooting in the dark for this one.
