### ISSUE TITLE
MachineClean oesn't seem to work! (Now on Alfred 3)

### ISSUE THREAD

**Issue by rEes9P** [vitorgalvao/alfred-workflows#31]
Hi,

I just upgraded to Alfred 3 and downloaded the latest version of MachineClean but it doesn't seem to work. It starts and asks for my username and password but doesn't actually lock the keys. Also, it disregards the time I put in and defaults to 50 seconds. I'm using a Retina MacBook Pro (Mid 2015) in case that is pertinent.

Here is the debug.

> Starting debug for 'MachineClean'
> 
> [2017-03-17 14:13:39][input.keyword] Processing output of 'action.script' with arg '10'
> [2017-03-17 14:13:42][trigger.external] Processing output of 'input.scriptfilter' with arg ''
> [2017-03-17 14:13:42][input.scriptfilter] {
> "rerun" : 1,
> 
> "variables": {
>   "timer": "1"
> },
> 
> "items": [{
>   "title": "MachineClean",
>   "subtitle": "Unlocking in 50 seconds",
>   "icon": "icon.png"
> }]}
> [2017-03-17 14:13:43][input.scriptfilter] {
> "rerun" : 1,
> 
> "variables": {
>   "timer": "2"
> },
> 
> "items": [{
>   "title": "MachineClean",
>   "subtitle": "Unlocking in 49 seconds",
>   "icon": "icon.png"
> }]}
> [2017-03-17 14:13:44][input.scriptfilter] {
> "rerun" : 1,
> 
> "variables": {
>   "timer": "3"
> },
> 
> "items": [{
>   "title": "MachineClean",
>   "subtitle": "Unlocking in 48 seconds",
>   "icon": "icon.png"
> }]}
> [2017-03-17 14:13:45][input.scriptfilter] {
> "rerun" : 1,
> 
> "variables": {
>   "timer": "4"
> },
> 
> "items": [{
>   "title": "MachineClean",
>   "subtitle": "Unlocking in 47 seconds",
>   "icon": "icon.png"
> }]}
> [2017-03-17 14:13:47][input.scriptfilter] {
> "rerun" : 1,
> 
> "variables": {
>   "timer": "5"
> },
> 
> "items": [{
>   "title": "MachineClean",
>   "subtitle": "Unlocking in 46 seconds",
>   "icon": "icon.png"
> }]}
> [2017-03-17 14:14:32][action.script] Processing output of 'action.script' with arg '
> '
> [2017-03-17 14:14:33][action.script] Processing output of 'utility.hidealfred' with arg '
> '
> [2017-03-17 14:14:33][utility.hidealfred] Processing output of 'action.script' with arg '
> '

**Comment by vitorgalvao** [comment]
> it disregards the time I put in and defaults to 50 seconds.

It no longer works by inputting time. You have to change the default time in the Workflow Environment Variables, and it always uses that.

But [as I’ve mentioned](https://github.com/vitorgalvao/alfred-workflows/issues/29), I don’t intend to debug this workflow any more, since it working or not depends on your Mac model and I can’t accurately debug it without access to your machine.

At this point, for this Workflow I’ll take either a PR that fixes when it doesn’t work or a clue that helps me fix it. But I won’t try to keep debugging it.
