### ISSUE TITLE
CheckSpelling in spanish/pt

### ISSUE THREAD

**Issue by setegonz** [vitorgalvao/alfred-workflows#32]
This workflow works really well with English text, but I think that I'm missing something in the configuration to make this work with Spanish and Portuguese. Can you explain me in more detail how I can set up those languages?

Thaks for all those opersource projects that you have been  developing.

**Comment by vitorgalvao** [comment]
Look at the `Hotkey` nodes on the right. Double click any of them except the first, and on the `Prefix` you’ll see one of `en`, `fr`, `de`, `pt`, `es`. Assign them any keyboard shortcut you want.

When you activate the shortcut, the language in the `Prefix` will be the one used.

**Comment by setegonz** [comment]
I already did that but nothing happens when I activate the shortcut with action set to: "pass through workflow".
![screenshot](https://cloud.githubusercontent.com/assets/11341688/24824533/8a45765e-1be3-11e7-8f21-3ec8cc5cf3a4.png)

And when I set the action to "show alfred"  this happens
https://www.dropbox.com/s/kdiwxgum6tfgel3/Screenshot%202017-04-07%2022.46.02.JPG?dl=0
![screenshot](https://cloud.githubusercontent.com/assets/11341688/24824536/930cd2f0-1be3-11e7-831e-e55a2a9b8335.png)

**Comment by vitorgalvao** [comment]
> And when I set the action to "show alfred" this happens

Don’t change the options, or it won’t work.

I just confirmed it works for Spanish (conxeguir → conseguir), so whatever is happening is not a problem with the workflow.

**Comment by setegonz** [comment]
@vitorgalvao Thank you. I'm still having the same issue, but if yours works, definitely I'm doing something wrong.
