### ISSUE TITLE
Notificator doesn't work, complains about SyntaxError

### ISSUE THREAD

**Issue by pickx** [vitorgalvao/alfred-workflows#33]
The latest update of Notificator broke it for me, it doesn't post a Notification Center notification when it should, instead it pops up the following error:

![screen shot 2017-06-09 at 09 39 31](https://user-images.githubusercontent.com/4918121/26963947-194b511c-4cf8-11e7-8e72-b193b37650d8.png)

clicking Edit highlights the following line:

![screen shot 2017-06-09 at 09 39 51](https://user-images.githubusercontent.com/4918121/26963987-38c613a6-4cf8-11e7-8191-6c1007ff0dfd.png)

thanks. and thanks for developing very useful Alfred workflows.

**Comment by vitorgalvao** [comment]
What is your macOS version? And what’s DownVid’s version?

**Comment by pickx** [comment]
I'm using DownVid 1.21.7 on 10.11.6

Also, directly launching Notificator.app from the workflow's directory gives the same error.

**Comment by vitorgalvao** [comment]
> on 10.11.6

I have a feeling this might be the issue. In the highlighted line, what happens if you change `let` to `var`?

**Comment by pickx** [comment]
> change let to var

it works now! thank you.

**Comment by vitorgalvao** [comment]
Glad it’s working. Closing.
