### ISSUE TITLE
TemporaryEmail - forward.cat Email won't show up in clipboarb

### ISSUE THREAD

**Issue by bkroggel** [vitorgalvao/alfred-workflows#36]
Seems like there is an issue with the forward.cat email address. The alfred-workflow works absolutely fine but (at least for me) the forward.cat address won't get pushed to my clipboard and therefore I do have to open my email app in order to access the newly crated disposable email address.

However it seems like I do have found a minor tweak that solves this issue for me:

In line 21 (where the variable gets pushed to the clipboard):

_Instead of:_
`pbcopy <<< "${email}"`

_I modified this line to:_
`pbcopy <<< "$(tr [A-Z] [a-z] <<< "$escaped_email_name@forward.cat")"`

**Comment by vitorgalvao** [comment]
You indeed found a bug. Thank you.

Already pushed a fix.
