### ISSUE TITLE
Temporary email not created

### ISSUE THREAD

**Issue by morganestes** [vitorgalvao/alfred-workflows#37]
When I try to run the `tmpmail` workflow, it appears to run and tells me that the email address has been copied to the clipboard, but it opens a blank tab in Chrome and there's nothing on the clipboard.

I'm running v1.4.1 of the TemporaryEmail workflow in Alfred3.

**Comment by morganestes** [comment]
I found that cURL is reporting `curl: (60) SSL certificate problem: Invalid certificate chain` when trying to run it against the fake name generator site. Passing the `-k` flag in the script allows it to continue as expected, creates the email, and opens the website inbox.

**Comment by vitorgalvao** [comment]
I’d rather not allow insecure connections. Instead, I changed it so that service is no longer used, and it instead builds a random string.

Fixed version is already live.
