### ISSUE TITLE
run command doesn't seem to be working

### ISSUE THREAD

**Issue by nettad** [vitorgalvao/alfred-workflows#41]
I type .echo 'hello' and expect to see a notification with 'hello'. Instead i get a notification saying RunCommand Success - the command finished successfully.
When I click on the notification I get:
Error on line 10: Error: You need to give at least one argument from the CLI. You cannot run this by double-clicking the app bundle.

**Comment by vitorgalvao** [comment]
From the Workflow’s README:

> To get the output of the command as `Large Type`, use ⌘ when actioning it.

You need to `.echo 'hello'` and then <kbd>⌘</kbd><kbd>↩</kbd> instead of just <kbd>↩</kbd>.

**Comment by vitorgalvao** [comment]
I’ve improved the README to make this clearer: https://github.com/vitorgalvao/alfred-workflows/blob/master/RunCommand/README.md (near the bottom).

**Comment by nettad** [comment]
yeah...that's clearer. Thanks!
