### ISSUE TITLE
Doen't unlock the Keyboard anymore

### ISSUE THREAD

**Issue by FlavourDaveMasterDDissle-theDtotheissle** [vitorgalvao/alfred-workflows#42]
Just downloaded the new version and my keyboard remains locked after the countdown. (2016 MBP on 10.12.6) :/

**Comment by rgrtht** [comment]
Yeah me too

**Comment by vitorgalvao** [comment]
https://github.com/vitorgalvao/alfred-workflows/issues/31#issuecomment-287334987
