### ISSUE TITLE
unfreeze?

### ISSUE THREAD

**Issue by mateatslc** [vitorgalvao/alfred-workflows#43]
How do I "unfreeze" a frozen process?

**Comment by vitorgalvao** [comment]
Are you talking about [`AppFreeze`](https://github.com/vitorgalvao/alfred-workflows/tree/master/AppFreeze)?

Just `unfreeze` with the app as the frontmost.

**Comment by mateatslc** [comment]
No, I meant ProcessControl's `top` command.

**Comment by vitorgalvao** [comment]
Please be specific. There are over 40 distinct Workflows in this repo.

What do you mean by unfreezing a process? What did you do that you want to undo?

**Comment by mateatslc** [comment]
https://github.com/vitorgalvao/alfred-workflows/tree/master/ProcessControl

Never mind, I found what I was looking for: hit enter for further options! 👍
