### ISSUE TITLE
Icon on menu bar.

### ISSUE THREAD

**Issue by JuanluR8** [vitorgalvao/alfred-workflows#47]
It's not actually an issue, the workflow works perfectly, but it'd be amazing an icon on the upside menu bar showing when the cafeinate is active, because you can't know when it's or not working unless you activate/desactivate again.

**Comment by vitorgalvao** [comment]
> because you can't know when it's or not working unless you activate/desactivate again.

Yes, you can. When you type `coffee` it tells you immediately what action it’ll take if you action it, meaning the current active option is the opposite of that.

> it'd be amazing an icon on the upside menu bar showing when the cafeinate is active

It’d also be harder, take up more space, and require a full-fledged app to be bundled with the Workflow for that tiny feature.

Thank you for the suggestion, but it simply is not worth it.
