### ISSUE TITLE
RecentDownloads

### ISSUE THREAD

**Issue by kbecker87** [vitorgalvao/alfred-workflows#48]
Hi! I got a new MacBook and now the RecentDownloads Workflow does not work, debugging shows this error:

    [STDERR: input.scriptfilter] HTML/Entities.pm did not return a true value. BEGIN failed--compilation aborted.

I installed the latest workflow from Github. I’m on Alfred 3.5.1. Thanks for your help!

**Comment by vitorgalvao** [comment]
Try the version just released. The Workflow was rewritten from the ground up.
