### ISSUE TITLE
ShortFilms is not working anymore since mpv upgrade

### ISSUE THREAD

**Issue by gbstan** [vitorgalvao/alfred-workflows#49]
Hi Vitor,

It seems that the mpv upgrade from brew today broke the streaming capability of mpv with youtube-dl.

As a consequence, ShortFilms doesn't work anymore either.

I have filled in a bug report for mpv: https://github.com/mpv-player/mpv/issues/5193

You might want to chip in too if you have an idea of what broke.

Cheers,

Guy

**Comment by vitorgalvao** [comment]
I see the issue already has replies that address this.
