### ISSUE TITLE
Add ability to save screenshots locally to predefined place as well as Imgur

### ISSUE THREAD

**Issue by nikitavoloboev** [vitorgalvao/alfred-workflows#52]
* What Workflow the issue is about: WebScreenshot
* The Workflow’s version: 1.5.9
* Alfred’s version: 3.6
* macOS’ version: 10.11.6

This is a feature request to WebScreenshot workflow. 

I often like to make screenshots that I want to save both locally and also get an immediate Imgur link to share. Currently your workflow only does the second part really well.

Would it be possible to add a new action that will allow user to take a screenshot and then get a little prompt of what name the user wants to give to the screenshot and save the screenshot to a predefined folder user chooses (by default ~/Desktop). The workflow will then save the original screenshot to that location but will also upload it to Imgur and give a shareable link.

I would really appreciate this addition. Thank you.

**Comment by vitorgalvao** [comment]
I can see the case to having a Workflow Environment Variable that’ll set the behaviour to always or never saving the screenshot to the Desktop, but adding yet another trigger for that specific case is harder to justify. If you’re interested in the former, I can take a look.

> by default ~/Desktop

I’d be reluctant to make it configurable. The Desktop is a good default.

> then get a little prompt of what name the user wants to give to the screenshot

That one is not going to happen. The goal of the Workflow is to save time uploading screenshots, and that window would be annoying.

**Comment by nikitavoloboev** [comment]
> that’ll set the behaviour to always or never saving the screenshot to the Desktop

This won't work for me I am afraid. As I would like to have both of those options available to me as two separate `hotkeys` I can call.

I can fork `WebScreenshot` and make an internal copy that will try and do this I guess. Thank you for considering it.

**Comment by vitorgalvao** [comment]
Keeping the screenshot is easy. At the bottom of the `webscreenshot` script, add

```
cp "${screenshot_file}" "${HOME}/Desktop"
```

From then it’s easy to make the script take yet another argument (for saving or not) and have it save the screenshot only when the argument is present. Something like this (not tested) should work

```
shift
[[ "${1}" == 'keep_screeshot' ]] && mv "${screenshot_file}" "${HOME}/Desktop"
```

**Comment by nikitavoloboev** [comment]
Hey @vitorgalvao 

I updated the workflow to suit this use case for myself. But I created a new file for it and a new action as I need both.

[Here](https://i.imgur.com/KFINidg.png) is the workflow in case you want to add it to original workflow.
