### ISSUE TITLE
Issue running Plex Bookmarklet

### ISSUE THREAD

**Issue by typkrft** [vitorgalvao/alfred-workflows#53]
Please do not forget to include:

* What Workflow the issue is about:
Running "Plex It" Bookmarklet, getting Error: "[2018-02-13 13:32:23][ERROR: action.script] 209:322: execution error: Error on line 2: Error: Application isn't running. (-600) "
* The Workflow’s version:
1.2.0
* Alfred’s version:
3.5.1
* macOS’ version:
10.13.3

**Comment by vitorgalvao** [comment]
Unfortunately, I won’t be able to debug this. I don’t use Plex and it seems that to even get the bookmarklet I’d need an account, which I do not want. I can’t justify the time commitment on this one.

Don’t forget to try this with your web browser as the frontmost app, and if you’re using Safari, to activate “Allow JavaScript from Apple Events”.

**Comment by typkrft** [comment]
I don't think they error has anything to do with Plex. The error is in the code trying to get system events front most app, which was Google Chrome. I just tried it with a number of bookmarklets from https://www.hongkiat.com/blog/100-useful-bookmarklets-for-better-productivity-ultimate-list/ which do not require any account. I think this has to do with someway that "System Events" is handled in High Sierra. Just running the code in Script Editor produces the same results. 

Simply doing something like in Script Editor
tell application "System Events"
  key code 49
end tell
also produces the same error message

**Comment by vitorgalvao** [comment]
Are you on a multi-user Mac? I ask because I’ve seen weird AppleScript errors occur in such machines.

I’m pretty sure I have `AlfredBookmarklet` (as well as several other Workflows that do the same browser detection) users on High Sierra, and I’ve never encountered this error.

I’m also not on High Sierra yet, so I have no way to test if that is the problem.

**Comment by typkrft** [comment]
Interestingly enough, it is on a Brand new single user Macbook. Like just bought 2 days ago. I’ve seen some other users complaining about the same thing just searching around. It seems this issue started back 10.12 Sierra, which makes me wonder if it has something to do with SIP. The only things installed are Xcode , Spark, Alfred, and chrome. That’s okay though I don’t expect someone doing free work to debug my issues, just curious if maybe you had known something about it.

Best,
Brandon

**Comment by typkrft** [comment]
I just resolved it simply by Going to System Preferences > Privacy & Security > Accessiblity , Then unchecking and rechecking System Events. Just in case you run by it again.

Best,
Brandon

**Comment by vitorgalvao** [comment]
I do appreciate you opening a bug report. When it’s something I can reproduce, I’m glad to fix it. Great to see it’s been resolved. Enjoy the new Macbook!
