### ISSUE TITLE
New Feature: Include auth for uploading to personal accounts

### ISSUE THREAD

**Issue by joeynotjoe** [vitorgalvao/alfred-workflows#55]
I'm not sure how easy it is, but if you could implement the ability to upload screenshots to your own account, that would be terrific.

* What Workflow the issue is about: **WebScreenshot**
* The Workflow’s version: **1.5.9**
* Alfred’s version: **3.6.1**
* macOS’ version: **10.13.3**

**Comment by vitorgalvao** [comment]
https://www.alfredforum.com/topic/8385-webscreenshot-%E2%80%94-take-screenshots-directly-to-the-web/?tab=comments#comment-46289

> There’s no way to upload to a specific account. I just looked into it, and I don’t intend to add the option to do it. Reason being it can’t be completely automated. It will require manual labour on the user’s side (manually registering a new application with imgur and getting an API key) and that’s a bad experience on the user’s side, and one I wouldn’t be improving on since I don’t have an account.
>
> I will consider a PR if it’s well done and takes user experience into account, though.
