### ISSUE TITLE
DenteAzul: Toggles bluetooth off and then instantly turns it back on

### ISSUE THREAD

**Issue by nikitavoloboev** [vitorgalvao/alfred-workflows#61]
* Workflow name: DenteAzul
* Workflow version: v1.0.1
* Alfred version: 3.6.2
* macOS version: 10.11.6
* Command that failed: bt
* Debugger output:

```bash
Starting debug for 'DenteAzul'

[2018-05-28 17:10:38][input.keyword] Processing output of 'action.script' with arg ''
[2018-05-28 17:10:39][action.script] Processing output of 'action.script' with arg ''
```

My understanding was that if I just activate `bt` it would turn off bluetooth if it is currently on. Or it will turn on bluetooth if is already on. 

This doesn't happen. I found [this workflow](https://transfer.sh/tfbXy/Bluetooth-toggle.alfredworkflow) that works like this but I want to use yours as I like the icon. I also like the fact that you can pass in a query to turn on/off bluetooth for some time.

**Comment by nikitavoloboev** [comment]
Oh and the workflow uses [this command line tool](https://github.com/toy/blueutil) to do its thing.

**Comment by vitorgalvao** [comment]
Two reasons why I don’t use that CLI tool:

1. I’d rather not add extra tools when the task can be accomplished without them.
2. It does not toggle the bluetooth icon on the menubar, which is my favourite feature.

---

What happens if you run the code directly in AppleScript Editor (replace `{query}` with `0`)?

**Comment by nikitavoloboev** [comment]
Same thing happens. It turns of for 1 second and then turns back on.

Ran it like this:
![2018-05-28 at 17 31](https://user-images.githubusercontent.com/6391776/40621428-faeeed76-629c-11e8-9df2-102c298ba633.png)

**Comment by vitorgalvao** [comment]
Do you see the icon showing and disappearing? Would be easier if I could see a video where you show me the state in the preferences pane, run the code, then show the preferences pane again.

**Comment by nikitavoloboev** [comment]
[Here](https://www.youtube.com/watch?v=UqfsK4c8fNk) is the screencast.

The workflow just hides the icon, turns of bluetooth for a bit than turns it on.

I will use the workflow I originally sent though because I don't actually care for the icon showing. I hide it with Bartender already.

But the issue is still strange.

**Comment by vitorgalvao** [comment]
It is indeed weird. What happens if you just click that “Turn Bluetooth Off” (which is basically what the Workflow is doing)? Does it turn itself on as well?

> I hide it with Bartender already.

I also use Bartender. The reason I like the feature is I almost never have bluetooth on (so I don’t want the icon cluttering the menu bar) but when I do I want to see the icon (so I don’t forget to turn it off).

**Comment by nikitavoloboev** [comment]
I always use external keyboard so for me it's the other way round. 🙂 

> What happens if you just click that “Turn Bluetooth Off”

If I click that button it turns off bluetooth and doesn't turn it back on until I press the button again.

**Comment by vitorgalvao** [comment]
What if you use this

```applescript
on toggleBluetooth()
	tell application "System Preferences"
		reveal pane id "com.apple.preferences.Bluetooth"
		tell application "System Events" to tell process "System Preferences"
			try
				click button "Turn Bluetooth On" of window "Bluetooth"
			on error
				click button "Turn Bluetooth Off" of window "Bluetooth"
			end try
			click checkbox "Show Bluetooth in menu bar" of window "Bluetooth"
		end tell
		tell application "System Preferences" to quit
	end tell
end toggleBluetooth

toggleBluetooth()
```

And if that doesn’t work, what about this

```applescript
tell application "System Preferences"
	reveal pane id "com.apple.preferences.Bluetooth"
	tell application "System Events" to tell process "System Preferences"
		try
			click button "Turn Bluetooth On" of window "Bluetooth"
		on error
			click button "Turn Bluetooth Off" of window "Bluetooth"
		end try
		click checkbox "Show Bluetooth in menu bar" of window "Bluetooth"
	end tell
	tell application "System Preferences" to quit
end tell
```

**Comment by nikitavoloboev** [comment]
Both of them don't work for me. Just toggle bluetooth visibility on and off.

The workflow I linked about works perfectly for me so you can close this issue as it seems I am the only person who has this issue. 🙂
