### ISSUE TITLE
KeyCodes: Should copy the key code to clipboard

### ISSUE THREAD

**Issue by nikitavoloboev** [vitorgalvao/alfred-workflows#62]
I [modified the workflow](https://transfer.sh/YFqWZ/KeyCodes.alfredworkflow) to do that.

I actually expected the workflow to do that at first as it seems logical to quickly get a key code value for some key and move on.

**Comment by vitorgalvao** [comment]
I’d rather not. It’s an easy addition for those who want it, and some keys have more than one possible value.

**Comment by vitorgalvao** [comment]
I knew this sounded familiar. I already answered in https://github.com/vitorgalvao/alfred-workflows/pull/44.
