### ISSUE TITLE
MediaThorn cannot fetch information anymore?

### ISSUE THREAD

**Issue by gbstan** [vitorgalvao/alfred-workflows#64]
* Workflow name: Media Thorn
* Workflow version: v1.0.2
* Alfred version: 3.6.2
* macOS version: 10.13.6 (17G65)
* Command that failed: movie
* Debugger output: None

```
No visible output on the debugger. I have attached a screenshot to show what I see. All queries give a similar output, i.e. no information apart from the rating seems to be fetched.
```
[Screen Shot 2018-08-04 at 4 Aug 2018 - 20.33.54.pdf](https://github.com/vitorgalvao/alfred-workflows/files/2259723/Screen.Shot.2018-08-04.at.4.Aug.2018.-.20.33.54.pdf)

**Comment by vitorgalvao** [comment]
MetaCritic changed their layout. Unfortunately, their default results now show way less info, so some changes where in order. Now there’s a single `ratings` command that shows all media types.

Download is on the same URL. Thank you for reporting this.

**Comment by gbstan** [comment]
Thank you Vitor.

Strangely, for some searches nothing comes back. An example is "ratings Star Trek".

I am not quite sure why?

Here is the debug messages for the query: "ratings star trek"

Starting debug for 'MediaThorn'

[2018-08-05 11:24:26][ERROR: input.scriptfilter] Code 1: ./metacritic:26:in `block in <main>': undefined method `text' for nil:NilClass (NoMethodError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:239:in `block in each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:238:in `upto'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:238:in `each'
    from ./metacritic:23:in `<main>'

**Comment by vitorgalvao** [comment]
That was a small bug (bound to happen since the new layout is not yet fully tested). It happened when an item had no synopsis. Already fixed in the latest version that you can download now.

**Comment by gbstan** [comment]
Thanks Vitor
