### ISSUE TITLE
Feature request - Support Firefox in TemporaryEmail workflow

### ISSUE THREAD

**Issue by cpoissonnier** [vitorgalvao/alfred-workflows#65]
It would be great if TemporaryEmail supported as well Firefox. 

It can easily be done by adding ` || "${front_browser}" == 'firefox'` in the condition where Chrome is supported (in the bash script)

**Comment by vitorgalvao** [comment]
> It can easily be done by adding

Didn’t work. Unfortunately, can’t say I’m surprised.

Thank you for the interest, but until Firefox’s atrocious AppleScript support is fixed (which at this point I’m more inclined to think it will never happen), I can’t support it in my Workflows. It’s the sole reason I don’t even consider using it as my main browser.

**Comment by vitorgalvao** [comment]
> Thanks for your amazing workflows :)

Thank you for the kind words! I don’t do any tracking, so these are the only times I know of people using my Workflows.
