### ISSUE TITLE
THANK YOU!!!!! MAN HOW ARE YOU ALWAYS THE ALFRED SAVIOR GOD

### ISSUE THREAD

**Issue by rouzbeh84** [vitorgalvao/alfred-workflows#66]
YOU ARE THE BEST MAN!!!! CAN'T EXPRESS HOW HAPPY I AM YOU EXIST haha

![](https://media.giphy.com/media/LpDmTYtmOJLXxkMB3H/giphy.gif)

https://media.giphy.com/media/LpDmTYtmOJLXxkMB3H/giphy.gif

**Comment by rouzbeh84** [comment]
you can close this as soon as you see it. just wanted to show some love

**Comment by vitorgalvao** [comment]
Thank you for the kind words and enthusiasm, @rouzbeh84! These are the only moments where I know people use my stuff and find it useful.

**Comment by rgrtht** [comment]
I feel bad, Vítor, as I always try to let coders / designers / tradespeople / pornstars know when I appreciate their work. I should’ve done this long ago, but I also enjoy your fantastic work on the Alfred workflows. Number one workflow-maker in my opinion. Whenever I see an update to one of your workflows (which is done automatically thanks to you!) I get really excited. Makes Alfred worth using in my opinion.

Do you have a http://ko-fi.com profile or something? I’d like to give you a tip.

Many thanks,
Ed Pollitt

**Comment by vitorgalvao** [comment]
I was just checking old issues and found this one. Apologies for never having replied @rgrtht. That’s unlike me, and I have no idea how that happened (maybe it got lost in the amount of Homebrew notifications I deal with every day).

I’d also like to thank you for the kind words. I don’t have a ko-fi profile, [only paypal](https://github.com/vitorgalvao/alfred-workflows/blob/master/README.md) (and hopefully soon a Github donors account).

Thank you again to both of you.
