### ISSUE TITLE
NewFile alfred workflow: Cannot create files if names of directories contain spaces (could in previous versions of the workflow)

### ISSUE THREAD

**Issue by gbstan** [vitorgalvao/alfred-workflows#67]
* Workflow name: NewFile
* Workflow version: 1.2.3
* Alfred version: 3.7
* macOS version: 10.13.6
* Command that failed: nfo
* Debugger output:
touch: /Users/[redacted]/Test%Directory/test.txt: No such file or directory
The file  /Users/[redacted]/Test%Directory/test.txt does not exist.

```
Open the [debugger](http://support.alfredapp.com/workflows:debugger), set the log output to “All Information”, and post the output here, replacing this text but keeping the backticks.
```

**Comment by vitorgalvao** [comment]
Thank you for the report. It’s been fixed in version `1.2.4`.
