### ISSUE TITLE
FormatSize - viewport API returns internal server error

### ISSUE THREAD

**Issue by AnthoPakPak** [vitorgalvao/alfred-workflows#70]
Hey, thanks for your great work :) 

I've noticed that FormatSize workflow stopped working, because [http://viewportsizes.com](http://viewportsizes.com) isn't responding anymore. Could it be possible to replace with another website or use a saved csv file (i've noticed that you were using a csv file on this website) ? 

Thanks in advance :)

* Workflow name: FormatSize
* Workflow version:1.5.2
* Alfred version:3.7.1
* macOS version:10.14.1
* Command that failed:viewport
* Debugger output: not interesting, it just the web page of the Internal Server error

**Comment by vitorgalvao** [comment]
> replace with another website

I don’t know of another one, nor frankly do I want to search for it, as I never use that feature.

> or use a saved csv file

Don’t have it. If you can get me one, I’ll replace it.

Otherwise, I’ll wait a bit to see if they come back online, and if they don’t I’ll just remove it.

**Comment by vitorgalvao** [comment]
And thank you for a good bug report!

**Comment by AnthoPakPak** [comment]
Thanks for your answer :) 

Indeed I've just found in your repo an old `viewport.csv` file. I've updated it with newest iPhone models, as I'm primarily interested in iOS devices.
I've disabled updating from `viewportsizes.com` for now as they are offline.

It works nice :) 

You can find the file here (replace .txt with .csv) :
[viewport.txt](https://github.com/vitorgalvao/alfred-workflows/files/2637145/viewport.txt)
