### ISSUE TITLE
Have a problem with  MediaThron

### ISSUE THREAD

**Issue by zalewskigrzegorz** [vitorgalvao/alfred-workflows#74]
* Workflow name:
MediaThorn
* Workflow version:
1.04
* Alfred version:
Alfred 3.8
Build 959, Saturday 2nd Feb 2019
* macOS version:
macOS Mojave
Version 10.14.4 Beta (18E194d)
* Command that failed:
ratings Far cray
* Debugger output:
Starting debug for 'MediaThorn'

[2019-03-03 00:38:49][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:225:in `open_loop': redirection forbidden: http://www.metacritic.com/search/all/Far/results -> https://www.metacritic.com/search/all/Far/results (RuntimeError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:35:in `open'
	from ./metacritic:18:in `<main>'
```
Open the [debugger](http://support.alfredapp.com/workflows:debugger), set the log output to “All Information”, and post the output here, replacing this text but keeping the backticks.
```

**Comment by vitorgalvao** [comment]
Fixed. Download the latest version.
