### ISSUE TITLE
CardSearch Feature Request - Full Scryfall Syntax Support

### ISSUE THREAD

**Issue by curby** [vitorgalvao/alfred-workflows#76]
Would it be possible to support the full Scryfall search syntax?  As an example, in addition to finding `Inalla, Archmage Ritualist` by name, you could also do a search for `c=rub s:c17 o:token` within Alfred.

I realize that the lookup will require active Internet access and will take more time to complete, but one of Scryfall's best features is its powerful search syntax, and it would be great to leverage that. perhaps via a separate keyword search in Alfred.

Thanks!

**Comment by vitorgalvao** [comment]
It is possible, yes, but I’m not sure I’ll (re)add it. That is the way it used to work, though, so if you grab [this version](https://github.com/vitorgalvao/alfred-workflows/blob/b7cb1a7ad15bd5ab03152fbebeaeb6fd15a928a3/CardSearch/CardSearch.alfredworkflow?raw=true), it’ll work like you want.
