### ISSUE TITLE
WebScreenshot: Add ability to create authorized Imgur screenshots

### ISSUE THREAD

**Issue by nikitavoloboev** [vitorgalvao/alfred-workflows#78]
* Workflow name: WebScreenshot
* Workflow version: 1.5.10
* Alfred version: 4.0.2
* macOS version: 10.14.6

### Summary
 Currently all screenshots made are made anonymously. I would like for there to be a setting so I can authorize all screenshots made and have them be uploaded from my account.

Thank you.

**Comment by vitorgalvao** [comment]
[This has been discussed before](https://www.alfredforum.com/topic/8385-webscreenshot-%E2%80%94-take-screenshots-directly-to-the-web/?tab=comments#comment-46289).
