### ISSUE TITLE
Close tab option actually closes the current browser window with all its tabs

### ISSUE THREAD

**Issue by gbstan** [vitorgalvao/alfred-workflows#79]
* Workflow name: PlayAddress
* Workflow version: 1.0
* Alfred version: 4.0.2
* macOS version: 10.14.5

This workflow is great. One aspect that I noticed with Safari as a browser is that when the close_tab option is selected to "yes" the workflow will actually close the current window and all of its tabs. Is there a way to only close the current tab instead of the whole window?

**Comment by gbstan** [comment]
> yes

**Comment by vitorgalvao** [comment]
So it does. It’ve fixed it in the newest version. You can already download it.

**Comment by gbstan** [comment]
Cheers!
