### ISSUE TITLE
Can it use http or sock5 proxy?

### ISSUE THREAD

**Issue by laipz8200** [vitorgalvao/alfred-workflows#83]
#### Setup info

* Workflow name: DownVid
* Workflow version:
* Alfred version:
* macOS version:

#### Debugger output

```
Open the [debugger](http://support.alfredapp.com/workflows:debugger), set the log output to “All Information”, and post the output here, replacing this text but keeping the backticks.
```

**Comment by vitorgalvao** [comment]
It supports whatever [`youtube-dl`](https://youtube-dl.org/) does. I don’t intend to add support for specific flags for particular network configurations.
