### ISSUE TITLE
Set Banner to 'Temporary' view

### ISSUE THREAD

**Issue by corroc** [vitorgalvao/alfred-workflows#84]
Love this workflow. Any way to set Banner to temporary, to disappear after seconds? Similarly, have audio stop after one instance of the tone?

Thank you!

**Comment by vitorgalvao** [comment]
I have no idea what Workflow you’re referring to. **Please do not delete the template**. I need it to be able to help you.

**Comment by vitorgalvao** [comment]
Closing for lack of reply. If you comment with the necessary information, I’ll reopen.
