### ISSUE TITLE
possible issue when updating brew

### ISSUE THREAD

**Issue by marcuskwan** [vitorgalvao/alfred-workflows#86]
#### Setup info

* Workflow name:
* Workflow version:
* Alfred version:
* macOS version:

#### Debugger output

```
Open the [debugger](http://support.alfredapp.com/workflows:debugger), set the log output to “All Information”, and post the output here, replacing this text but keeping the backticks.
```

Had an issue where I installed something via Brew and the workflow wouldn't work. Tried reinstalling the workflow but it wouldn't work. Ended up opening the debugger and seeing blueutil wasn't recognized, so I installed and it ended up working. Hope you can let other people know if this is an issue for them, one of my fav workflows !

**Comment by vitorgalvao** [comment]
> one of my fav workflows

Thank you!

The official fix is https://github.com/vitorgalvao/alfred-workflows/issues/85#issuecomment-527420849. If I get another person with the issue, I’ll make it the solution more prominent or add some temporary code to fix it.
