### ISSUE TITLE
UploadFile: Could not save metadata (transfer.sh).

### ISSUE THREAD

**Issue by miltonardila** [vitorgalvao/alfred-workflows#87]
#### Setup info

* Workflow name: UploadFile
* Workflow version: v1.6.0
* Alfred version: 4.0.4
* macOS version: 10.14.6

#### Description of issue

Hi. When the workflow has uploaded the file, it doesn't copy the url. The result is the following "Could not save metadata".

#### Debugger output

```
[14:27:44.601] Logging Started...
[14:28:03.755] UploadFile[File Action] Processing complete
[14:28:03.759] UploadFile[File Action] Passing output '/Users/miltonardila/Documents/SolucionesK/Clientes/Carcaixent CF/Colaboradores.zip' to Run Script
[14:28:11.354] STDERR: UploadFile[Run Script] /Users/miltonardila/Documents/SolucionesK/Clientes/Carcaixent CF/Colaboradores.zip
[14:28:11.357] UploadFile[Run Script] Processing complete
[14:28:11.358] UploadFile[Run Script] Passing output '' to Run Script
```

**Comment by vitorgalvao** [comment]
That’s a problem with `transfer.sh`. Either change the `upload_file_to` Workflow Environment Variable or wait it out for them to fix the server problems.

**Comment by miltonardila** [comment]
Hi, I spoke to transfer.sh support and they say it works correctly.

However it tells me to use alpha.transfer.sh that works better.
How can I change the variable to use this service?
I tried to change it by editing the current one, but it sends me to bayfiles.com

Greetings and thanks.

**Comment by vitorgalvao** [comment]
> I spoke to transfer.sh support and they say it works correctly.

It doesn’t. A moment ago, even the website itself wasn’t loading. Ever since they were acquired these issues are a constant. I’ve had a few Twitter conversations with them about it. Yesterday, neither the alpha nor the non-alpha version worked.

I didn’t add alpha support because I thought they had dealt with the issues. It’s added now, you’ll find it in the just released version.

**Comment by miltonardila** [comment]
Hi Vitor,
Thank you for your support.

It seems that the new owners of transfer.sh are dedicating themselves to new projects, but they say they will stay alive.

I have upgraded to version 1.6.2 and everything seems to be going well. As long as the server is working as you say.

Can I use this thread to ask how to configure "oneupdater"? so that all your workflows (which I love!) continue working?

**Comment by vitorgalvao** [comment]
> It seems that the new owners of transfer.sh are dedicating themselves to new projects, but they say they will stay alive.

They seem like nice people and I believe they want transfer.sh to keep going. But at the same time it’s true that I don’t recall any major issues before the acquisition, and several after. Which is weird because the company that now controls the website is a cloud hosting company. Them being unreliable is the worst kind of publicity; I have no desire to try their paid services.

> Can I use this thread to ask how to configure "oneupdater"? so that all your workflows (which I love!) continue working?

Thank you for the kind words, but I don’t understand the question. You don’t need to do anything to configure OneUpdater in my Workflows.

**Comment by miltonardila** [comment]
ok I understand.  

My question is because I cannot update automatically.  I must be aware of your new releases to update manually.  and also in your list you have a workflow that is called the same.

So I thought I had to install that workflow and set it up separately.

**Comment by vitorgalvao** [comment]
> I must be aware of your new releases to update manually.

You do not. Updates are downloaded automatically and opened for you to install them. But each Workflow only checks for updates once every four days and only when invoked.

**Comment by miltonardila** [comment]
Ohhh, perfect  Some of the two situations may not have happened before.  That you did not invoke at the precise moment when the update is to be installed.  

Thank you again for your support and congratulate you for this work you do.

**Comment by vitorgalvao** [comment]
> That you did not invoke at the precise moment when the update is to be installed.

That’s not what I mean.

Whenever you invoke the Workflow, `OpenUdater` asks “have I checked for updates in the last four days?” If yes, it skips the check, otherwise it does it. If you call a Workflow once every six days (for example), then it would check every time.

**Comment by miltonardila** [comment]
Ok I understand.
I will be pending for an upcoming update and see the behavior.  
and any questions I ask.
