### ISSUE TITLE
pa doesn't work with Brave Browser

### ISSUE THREAD

**Issue by ubuntudroid** [vitorgalvao/alfred-workflows#91]
#### Setup info

* Workflow name: pa
* Workflow version: 1.6.0
* Alfred version: 4.0.4
* macOS version: 10.14.6

#### Description of issue

When running the _pa_ workflow with the Brave Browser open the URL isn't prefilled into the PinPlus.app window. It works fine with other browsers like Vivaldi.

#### Debugger output

```
[18:25:11.781] Logging Started...
[18:25:17.022] PinPlus[Keyword] Processing complete
[18:25:17.025] PinPlus[Keyword] Passing output '' to Run Script
```

**Comment by vitorgalvao** [comment]
Brave Browser seems to have changed their AppleScript / JXA interpreter. When we ask the system for the app’s name, it returns `Brave Browser`, but when we want to send it JXA commands, it only responds to `Brave`.

I’ll consider this a bug on their side. You may wish to report it to them.

**Comment by ubuntudroid** [comment]
Ah, interesting. Thanks for checking so quickly! Will forward this to them.

**Comment by ubuntudroid** [comment]
I've opened an issue for this over at the brave project: https://github.com/brave/brave-browser/issues/6330
