### ISSUE TITLE
DownVid and macOS Catalina

### ISSUE THREAD

**Issue by peterolle** [vitorgalvao/alfred-workflows#92]
When executing: The UR is Invalid

Any fix for this?

Thanks.

**Comment by vitorgalvao** [comment]
Please follow the template.

**Comment by peterolle** [comment]
Can you please elaborate on that? I download it, run it and fails. Which template, what to do or modify?

Thanks.

**Comment by vitorgalvao** [comment]
When you open an issue on this repo, you’re presented with a template requesting specific information. I need that before considering your issue.
