### ISSUE TITLE
Can't find Rename in action list

### ISSUE THREAD

**Issue by spring-haru** [vitorgalvao/alfred-workflows#95]
#### Setup info

* Workflow name: RenameAction
* Workflow version: v0.0.0
* Alfred version: 4.0.5
* macOS version: Catalina

#### Description of issue

I cannot find `Rename` in the action list after choose a file/directory.

#### Debugger output

```
Open the [debugger](http://support.alfredapp.com/workflows:debugger), set the log output to “All Information”, and post the output here, replacing this text but keeping the backticks.
```

**Comment by vitorgalvao** [comment]
> * Workflow version: v0.0.0

You downloaded the Workflow from Packal. The README in it tells you how to proceed. Either run `update` or [download the correct version](https://github.com/vitorgalvao/alfred-workflows/raw/master/RenameAction/RenameAction.alfredworkflow).

Also, consider abandoning Packal. It’s dead, buggy, breaking left and right, and its developer hasn’t touched it in years. Similar sites are lacklustre. The place to find Workflows and expect some support is [the forum](https://www.alfredforum.com/).
